export const countryCodes = [
  { code: '+91', name: 'India' },
  { code: '+44', name: 'United Kingdom' },
  { code: '+1', name: 'United States/Canada' },
  { code: '+61', name: 'Australia' },
  { code: '+81', name: 'Japan' },
  { code: '+49', name: 'Germany' },
  { code: '+33', name: 'France' },
  { code: '+39', name: 'Italy' },
  { code: '+86', name: 'China' },
  { code: '+971', name: 'United Arab Emirates' },
  { code: '+92', name: 'Pakistan' },
  { code: '+94', name: 'Sri Lanka' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+60', name: 'Malaysia' },
  { code: '+62', name: 'Indonesia' },
  { code: '+63', name: 'Philippines' },
  { code: '+64', name: 'New Zealand' },
  { code: '+65', name: 'Singapore' },
  { code: '+966', name: 'Saudi Arabia' },
  { code: '+20', name: 'Egypt' },
  { code: '+234', name: 'Nigeria' },
  { code: '+27', name: 'South Africa' },
  { code: '+7', name: 'Russia' },
  { code: '+55', name: 'Brazil' },
  { code: '+34', name: 'Spain' },
  { code: '+52', name: 'Mexico' },
  { code: '+353', name: 'Ireland' },
  { code: '+41', name: 'Switzerland' },
  { code: '+31', name: 'Netherlands' },
  { code: '+48', name: 'Poland' },
  { code: '+351', name: 'Portugal' },
  { code: '+46', name: 'Sweden' },
  { code: '+47', name: 'Norway' },
  { code: '+358', name: 'Finland' },
  { code: '+90', name: 'Turkey' },
  { code: '+66', name: 'Thailand' },
  { code: '+84', name: 'Vietnam' },
  { code: '+254', name: 'Kenya' },
  { code: '+256', name: 'Uganda' },
  { code: '+255', name: 'Tanzania' },
  { code: '+98', name: 'Iran' },
  { code: '+964', name: 'Iraq' },
  { code: '+968', name: 'Oman' },
  { code: '+974', name: 'Qatar' },
  { code: '+973', name: 'Bahrain' },
  { code: '+972', name: 'Israel' },
  { code: '+82', name: 'South Korea' },
  { code: '+212', name: 'Morocco' },
  { code: '+54', name: 'Argentina' },
  { code: '+56', name: 'Chile' },
  { code: '+57', name: 'Colombia' },
  { code: '+64', name: 'New Zealand' },
  { code: '+351', name: 'Portugal' },
  { code: '+358', name: 'Finland' },
];
